/**
 * The Phase 2 gate: prompt construction must be byte-identical to the Python reference.
 *
 * `test/fixtures/ref/prepare.json` is generated by `tools/reference/make_prepare_fixture.py`, which
 * drives the real `laya_mlx` package over the tiny fixture tokenizer. It pins ids, markers, the
 * option-budget stats and the truncation stats for every question of seven cases — including the
 * ones the three parity cases do not reach: state truncation in both directions, option collapsing
 * under a tight head budget, and rendered option strings.
 *
 * Because the tiny checkpoint's `max_len` is 64 and its `head_max_len` is 32, the truncation and
 * collapsing paths actually fire here instead of being unreachable branches.
 *
 * If this fails, fix the port — do not regenerate the fixture.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { beforeAll, describe, expect, it } from "vitest";
import { serializeState } from "./ppjson.js";
import { QTYPES, renderOptions, toInternal } from "./questions.js";
import { buildPrefix, finishSequence, type PrefixStats, type TinyTokenizer } from "./sequence.js";
import { loadTokenizer } from "./tokenizer.js";

interface FixtureItem {
  qtype: number;
  ids: number[];
  markers: number[];
  options: PrefixStats;
  state_stats: {
    state_tokens: number;
    state_tokens_used: number;
    state_tokens_dropped: number;
    truncated: boolean;
  };
  rendered_options: string[];
}

interface Fixture {
  generator: string;
  reference: string;
  max_len: number;
  head_max_len: number;
  cases: {
    label: string;
    state: unknown;
    questions: Record<string, unknown>;
    items: Record<string, FixtureItem>;
  }[];
}

const fixture: Fixture = JSON.parse(
  readFileSync(
    fileURLToPath(new URL("../../../../test/fixtures/ref/prepare.json", import.meta.url)),
    "utf8",
  ),
) as Fixture;

let tokenizer: TinyTokenizer;

beforeAll(() => {
  tokenizer = loadTokenizer(
    fileURLToPath(new URL("../../../../test/fixtures/tiny/tokenizer", import.meta.url)),
  );
});

describe("golden prepare() against the Python reference", () => {
  it("was generated from laya_mlx, not from a previous TypeScript port", () => {
    expect(fixture.reference).toBe("laya_mlx");
    expect(fixture.generator).toBe("tools/reference/make_prepare_fixture.py");
    expect(fixture.cases.length).toBeGreaterThanOrEqual(7);
  });

  it("exercises the paths it claims to", () => {
    const items = fixture.cases.flatMap((c) => Object.values(c.items));
    // Guards against the fixture quietly going soft — e.g. a head budget so large that options
    // never collapse, leaving the interesting branches untested.
    expect(items.some((i) => i.options.tokens_per_option !== null)).toBe(true);
    expect(items.some((i) => i.options.options_distinct < i.options.options)).toBe(true);
    expect(items.some((i) => i.state_stats.truncated)).toBe(true);
    expect(items.some((i) => i.state_stats.state_tokens_dropped > 0)).toBe(true);
    expect(items.some((i) => i.markers.length >= 12)).toBe(true);
  });

  for (const testCase of fixture.cases) {
    describe(testCase.label, () => {
      for (const [qid, expected] of Object.entries(testCase.items)) {
        it(`${qid}: ids, markers and stats match`, () => {
          const question = toInternal(testCase.questions[qid]);

          expect(QTYPES[question.t]).toBe(expected.qtype);
          expect(renderOptions(question)).toEqual(expected.rendered_options);

          const prefix = buildPrefix(tokenizer, question, fixture.head_max_len, true);
          expect(prefix.stats).toEqual(expected.options);

          const stateIds = tokenizer.encode(
            serializeState(testCase.state).replaceAll(tokenizer.mask_token, " "),
          );
          const built = finishSequence(
            tokenizer,
            prefix.ids,
            prefix.markers,
            stateIds,
            fixture.max_len,
            Array.isArray(testCase.state),
          );

          expect(built.ids).toEqual(expected.ids);
          expect(built.markers).toEqual(expected.markers);
          expect(built.stats).toEqual(expected.state_stats);
        });
      }
    });
  }
});
